import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
      container: {flex: 1, backgroundColor: '#fff'},
  header: {
    backgroundColor: '#ff6b00',
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerLeft: {flex: 1},
  headerRight: {justifyContent: 'center', alignItems: 'center'},
  name: {color: '#fff', fontSize: 24, fontWeight: '700'},
  subname: {color: '#fff', opacity: 0.9, marginTop: 4},
  metaRow: {flexDirection: 'row', marginTop: 10, alignItems: 'center'},
  metaText: {color: '#fff', opacity: 0.95},
  ratingBox: {
    backgroundColor: 'rgba(255,255,255,0.15)',
    padding: 8,
    borderRadius: 8,
    alignItems: 'center',
  },
  rating: {color: '#fff', fontWeight: '700'},
  reviews: {color: '#fff', fontSize: 12, opacity: 0.9},

  actions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 16,
  },
  primaryButton: {
    backgroundColor: '#ff6b00',
    paddingVertical: 12,
    paddingHorizontal: 22,
    borderRadius: 8,
    flex: 1,
    marginRight: 8,
    alignItems: 'center',
  },
  primaryButtonText: {color: '#fff', fontWeight: '700'},
  outlineButton: {
    borderWidth: 1,
    borderColor: '#ff6b00',
    paddingVertical: 12,
    paddingHorizontal: 22,
    borderRadius: 8,
    flex: 1,
    marginLeft: 8,
    alignItems: 'center',
  },
  outlineButtonText: {color: '#ff6b00', fontWeight: '700'},

  sectionTitle: {fontSize: 18, fontWeight: '700', paddingHorizontal: 16, marginTop: 8, marginBottom: 8},

  card: {
    flexDirection: 'row',
    backgroundColor: '#fff7ee',
    marginHorizontal: 16,
    marginBottom: 12,
    borderRadius: 12,
    overflow: 'hidden',
    elevation: 2,
  },
  cardImage: {width: 90, height: 90},
  cardContent: {flex: 1, padding: 12},
  cardHeader: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center'},
  cardTitle: {fontWeight: '700'},
  tag: {
    borderWidth: 1,
    borderColor: '#ff8a50',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 12,
  },
  tagText: {color: '#ff8a50', fontSize: 12},
  cardSubtitle: {color: '#666', marginTop: 6},
  cardPrice: {color: '#d35400', fontWeight: '700', marginTop: 8},

  promoCard: {
    backgroundColor: '#fff3eb',
    marginHorizontal: 16,
    borderRadius: 12,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
  },
  promoLeft: {marginRight: 12},
  promoCircle: {
    backgroundColor: '#ff8a50',
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  promoPercent: {color: '#fff', fontWeight: '700', fontSize: 20},
  promoRight: {},
  promoTitle: {fontWeight: '700'},
  promoSubtitle: {color: '#666', marginTop: 4},
})